on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  go-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.2.5
          terraform_wrapper: false

      - name: Run tf Tests
        working-directory: test/unit-test/
        run: |
          terraform init
          terraform validate

      - name: Run Gatekeeper Tests
        working-directory: test/suite
        run: |
          # install gator via brew
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh
          test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
          test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          test -r ~/.bash_profile && echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bash_profile
          echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.profile

          brew install gator

          gator verify ./...

